# Generated by Django 4.2 on 2023-04-26 16:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('plate_no', models.CharField(max_length=20)),
                ('vin_number', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('car_model_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('car_model', models.CharField(max_length=100, verbose_name='Car model')),
                ('year', models.DateField(null=True, verbose_name='Made on:')),
                ('engine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(default=datetime.datetime(2023, 4, 26, 19, 33, 26, 703269))),
                ('total_price', models.FloatField()),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carservice.car')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('service_price_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(verbose_name='Price')),
                ('cars', models.ManyToManyField(to='carservice.carmodel')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carservice.service')),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('order_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carservice.order')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carservice.service')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carservice.carmodel'),
        ),
    ]
