# Generated by Django 4.2 on 2023-04-26 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vin_number',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 19, 51, 45, 548944)),
        ),
    ]
